#配置使用哪种配置
spring:
  #profiles:
   # active: dev
    #数据库的相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      #在控制台打印sql
    show-sql: true